Riya week 2
Yuggupta27/odf-interns pull request #5
Opened 2022-01-17 11:48 UTC by riya-singhal31

Title: Made new branch

This is my Pull Request message, I have made the separate branch for week 2 and have done the recommended corrections.

2022-01-18 05:47 UTC, subhamkrai requested changes
remove unwanted files

2022-01-18 06:04 UTC, riya-singhal31 commented
> remove unwanted files

Done

2022-01-20 02:59 UTC, subhamkrai requested changes
this should not be a new commit. Please remove this in the commit where you added it.

2022-01-20 03:13 UTC, Yuggupta27 requested changes
Leave an empty space before starting a comment.

2022-01-20 03:13 UTC, Yuggupta27 commented on Riya Singhal/Golang/generalSyntax.go
> +	//for loop as while loop
Leave an empty space before starting a comment.
`// comment` looks lunch cleaner than `//comment`

Please update this here and everywhere else

2022-06-03 05:24 UTC, merged